client:
  message: Development Env Client Microservices successfully invoking Cloud Config Server to fetch the properties from Git location
    
database:
  connection: jdbc:oracle:thin:@10.232.80.116:1521:orcl1-dev
  host: 127.0.0.1
  port: 1521
