servlet:
  contextPath: /payments-service
  error:
    whitelabel:
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true
    connection-timeout: 30000
    max-connections: 8192
    accept-count: 100
    processor-cache: 200
    threads:
      max: 200
      min-spare: 10
